package com.multiplatform.webview.request.internal

import com.multiplatform.webview.request.WebViewSchemeOutcome
import com.multiplatform.webview.request.WebViewSchemeResponse
import com.multiplatform.webview.request.toAsciiLowercase

internal fun validateSchemeResponse(
    response: WebViewSchemeResponse,
    isHead: Boolean,
): Pair<WebViewSchemeResponse, WebViewSchemeOutcome.Response> {
    require(response.statusCode in 200..299 || response.statusCode in 400..599) {
        "Custom scheme responses only support 2xx, 4xx, and 5xx statuses"
    }
    require(response.mimeType.isNotBlank()) { "mimeType must not be blank" }
    response.reasonPhrase?.let { reason ->
        require(reason.isNotEmpty() && reason.all { it.code in 0x20..0x7e }) {
            "reasonPhrase must be non-empty printable ASCII"
        }
    }

    val headerNames = mutableSetOf<String>()
    response.headers.forEach { (name, value) ->
        require(name.hasNoLineBreak() && value.hasNoLineBreak()) {
            "Header names and values must not contain CR or LF"
        }
        val normalizedName = name.toAsciiLowercase()
        require(headerNames.add(normalizedName)) { "Duplicate response header: $name" }
        require(normalizedName != "content-type" && normalizedName != "content-length") {
            "Content-Type and Content-Length are generated by the library"
        }
    }

    val bodySize =
        if (response.statusCode == 204 || response.statusCode == 205) 0 else response.body.size
    val deliveredBody =
        if (isHead || response.statusCode == 204 || response.statusCode == 205) {
            EMPTY_BODY
        } else {
            response.body
        }
    val reasonPhrase = response.reasonPhrase ?: defaultReasonPhrase(response.statusCode)
    val headers =
        buildMap {
            putAll(response.headers)
            put(
                "Content-Type",
                response.mimeType + (response.encoding?.let { "; charset=$it" } ?: ""),
            )
            put("Content-Length", bodySize.toString())
        }
    val normalized =
        WebViewSchemeResponse(
            body = deliveredBody,
            mimeType = response.mimeType,
            encoding = response.encoding,
            statusCode = response.statusCode,
            reasonPhrase = reasonPhrase,
            headers = headers,
        )
    return normalized to
        WebViewSchemeOutcome.Response(
            statusCode = normalized.statusCode,
            reasonPhrase = reasonPhrase,
            mimeType = normalized.mimeType,
            encoding = normalized.encoding,
            headers = normalized.headers,
            bodySize = bodySize,
        )
}

private fun String.hasNoLineBreak() = '\r' !in this && '\n' !in this

internal fun defaultReasonPhrase(statusCode: Int): String =
    when (statusCode) {
        200 -> "OK"
        201 -> "Created"
        202 -> "Accepted"
        203 -> "Non-Authoritative Information"
        204 -> "No Content"
        205 -> "Reset Content"
        206 -> "Partial Content"
        400 -> "Bad Request"
        401 -> "Unauthorized"
        403 -> "Forbidden"
        404 -> "Not Found"
        405 -> "Method Not Allowed"
        408 -> "Request Timeout"
        409 -> "Conflict"
        410 -> "Gone"
        413 -> "Content Too Large"
        415 -> "Unsupported Media Type"
        422 -> "Unprocessable Content"
        429 -> "Too Many Requests"
        500 -> "Internal Server Error"
        501 -> "Not Implemented"
        502 -> "Bad Gateway"
        503 -> "Service Unavailable"
        504 -> "Gateway Timeout"
        else -> "Status"
    }

private val EMPTY_BODY = byteArrayOf()
